"""
Ledger management for tracking auto-generated annotations.
"""

import json
import os
from typing import Dict, List

from .utils import load_labelme_json, shapes_hash


LEDGER_FILENAME = ".sam2_auto.json"
LEGACY_FLAG = "sam2_auto"  # Old flag-based marking (for backward compatibility)


def load_ledger(directory: str) -> Dict[str, str]:
    """Load auto-generation ledger from directory.

    Args:
        directory: Path to annotation directory

    Returns:
        Dict mapping stem -> shapes_hash for auto-generated files
    """
    ledger_path = os.path.join(directory, LEDGER_FILENAME)
    try:
        with open(ledger_path, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def save_ledger(directory: str, ledger: Dict[str, str]) -> None:
    """Save auto-generation ledger to directory.

    Args:
        directory: Path to annotation directory
        ledger: Dict mapping stem -> shapes_hash
    """
    ledger_path = os.path.join(directory, LEDGER_FILENAME)
    temp_path = ledger_path + ".tmp"

    with open(temp_path, "w", encoding="utf-8") as f:
        json.dump(ledger, f, indent=1, sort_keys=True)

    os.replace(temp_path, ledger_path)


def is_auto_generated(json_path: str, ledger: Dict[str, str]) -> bool:
    """Check if annotation was auto-generated and unmodified.

    Uses content hash for robust detection. Falls back to legacy flag
    for files generated by older versions.

    Args:
        json_path: Path to LabelMe JSON file
        ledger: Ledger dict from load_ledger()

    Returns:
        True if auto-generated and not manually edited
    """
    stem = os.path.splitext(os.path.basename(json_path))[0]

    try:
        doc = load_labelme_json(json_path)
    except Exception:
        return False

    shapes = doc.get("shapes", [])

    # Primary method: check content hash
    if stem in ledger:
        return ledger[stem] == shapes_hash(shapes)

    # Fallback: legacy flag-based detection
    return bool(doc.get("flags", {}).get(LEGACY_FLAG))


def mark_as_auto(
    json_path: str,
    shapes: List[dict],
    ledger: Dict[str, str]
) -> None:
    """Mark annotation as auto-generated in ledger.

    Args:
        json_path: Path to LabelMe JSON file
        shapes: List of shapes that were written
        ledger: Ledger dict (modified in-place)
    """
    stem = os.path.splitext(os.path.basename(json_path))[0]
    ledger[stem] = shapes_hash(shapes)


def is_manual_seed(json_path: str, ledger: Dict[str, str]) -> bool:
    """Check if annotation is a manual seed (exists but not auto-generated).

    Args:
        json_path: Path to LabelMe JSON file
        ledger: Ledger dict from load_ledger()

    Returns:
        True if file exists with shapes and is not auto-generated
    """
    if not os.path.exists(json_path):
        return False

    try:
        doc = load_labelme_json(json_path)
        shapes = doc.get("shapes", [])
    except Exception:
        return False

    if not shapes:
        return False

    return not is_auto_generated(json_path, ledger)
